-- ===========================================================================
-- Cricket Arena — complete database setup
--
-- Generated by concatenating every file in migrations/ in order.
-- Paste the whole thing into the Supabase SQL editor and press Run once.
-- Safe to run on a brand new project. Do NOT run twice.
-- ===========================================================================


-- >>> BEGIN migrations/20260101000000_init.sql

-- ============================================================================
-- Cricket Arena — core schema
-- ============================================================================
-- Design notes
--
-- 1. A match is an event log. `deliveries` is the source of truth; scorecards,
--    standings and career figures are all derived. That gives free undo,
--    auditable corrections, and lets an offline device replay its queue safely.
--
-- 2. `wide_runs` and `no_ball_runs` are stored as ABSOLUTE totals including the
--    automatic penalty, so the generated total columns below need no knowledge
--    of the competition's rules. The client converts to and from the domain
--    representation (where `wide` means "additional runs run").
--
-- 3. A `player` is an entity inside an organisation and only optionally linked
--    to an auth user. Most club cricketers never sign in.
-- ============================================================================

-- `gen_random_uuid()` is core Postgres from 13 onwards, so no extension is
-- required. Everything below is plain SQL and runs on any modern Postgres.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type app_role as enum (
  'platform_admin',
  'tournament_admin',
  'scorer',
  'umpire',
  'team_manager',
  'captain',
  'player',
  'fan',
  'stream_operator'
);

create type tournament_format as enum (
  'round_robin',
  'double_round_robin',
  'groups',
  'knockout',
  'league_playoffs',
  'custom'
);

create type match_format as enum ('T10', 'T20', 'ODI', 'TEST', 'TAPE_BALL', 'CUSTOM');

create type tournament_status as enum ('draft', 'registration', 'active', 'completed', 'archived');

create type match_status as enum (
  'scheduled',
  'toss',
  'live',
  'innings_break',
  'completed',
  'abandoned',
  'cancelled',
  'walkover'
);

create type match_stage as enum (
  'league',
  'group',
  'quarter_final',
  'semi_final',
  'final',
  'third_place',
  'eliminator',
  'qualifier',
  'friendly'
);

create type result_kind as enum ('win', 'tie', 'draw', 'no_result', 'abandoned', 'walkover');

create type dismissal_kind as enum (
  'bowled',
  'caught',
  'caught_behind',
  'caught_and_bowled',
  'lbw',
  'stumped',
  'hit_wicket',
  'run_out',
  'obstructing_the_field',
  'hit_ball_twice',
  'timed_out',
  'retired_out',
  'retired_not_out'
);

create type innings_end_reason as enum (
  'all_out',
  'overs_complete',
  'target_reached',
  'declared',
  'forfeited',
  'abandoned'
);

create type batting_style as enum ('right_hand', 'left_hand');

create type bowling_style as enum (
  'right_arm_fast',
  'right_arm_medium',
  'right_arm_off_break',
  'right_arm_leg_break',
  'left_arm_fast',
  'left_arm_medium',
  'left_arm_orthodox',
  'left_arm_chinaman',
  'none'
);

create type player_role as enum ('batter', 'bowler', 'all_rounder', 'wicket_keeper', 'wicket_keeper_batter');

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

create table profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  handle text unique,
  avatar_url text,
  phone text,
  city text,
  country text,
  is_platform_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table profiles is 'Public profile mirroring auth.users. Created automatically on sign up.';

-- ---------------------------------------------------------------------------
-- Organisations (a club, league body or tournament operator)
-- ---------------------------------------------------------------------------

create table organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  logo_url text,
  city text,
  country text,
  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table organization_members (
  organization_id uuid not null references organizations (id) on delete cascade,
  user_id uuid not null references profiles (id) on delete cascade,
  role app_role not null default 'fan',
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create index on organization_members (user_id);

-- ---------------------------------------------------------------------------
-- Venues
-- ---------------------------------------------------------------------------

create table venues (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  name text not null,
  city text,
  address text,
  pitch_type text,
  floodlights boolean not null default false,
  created_at timestamptz not null default now()
);

create index on venues (organization_id);

-- ---------------------------------------------------------------------------
-- Teams and players
-- ---------------------------------------------------------------------------

create table teams (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  name text not null,
  short_name text not null,
  logo_url text,
  primary_color text not null default '#20D78A',
  home_venue_id uuid references venues (id) on delete set null,
  manager_id uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (organization_id, name)
);

create index on teams (organization_id);

create table players (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  -- Set when this cricketer also has an account on the platform.
  user_id uuid references profiles (id) on delete set null,
  full_name text not null,
  display_name text,
  jersey_number int,
  date_of_birth date,
  role player_role not null default 'batter',
  batting_style batting_style not null default 'right_hand',
  bowling_style bowling_style not null default 'none',
  photo_url text,
  phone text,
  /* Fantasy credit value, 5.0 - 12.0 */
  credit_value numeric(4, 1) not null default 8.0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index on players (organization_id);
create index on players (user_id);

create table team_members (
  team_id uuid not null references teams (id) on delete cascade,
  player_id uuid not null references players (id) on delete cascade,
  is_captain boolean not null default false,
  is_vice_captain boolean not null default false,
  is_wicket_keeper boolean not null default false,
  joined_at timestamptz not null default now(),
  primary key (team_id, player_id)
);

create index on team_members (player_id);

-- Only one captain per team.
create unique index team_one_captain on team_members (team_id) where is_captain;

-- ---------------------------------------------------------------------------
-- Tournaments
-- ---------------------------------------------------------------------------

create table tournaments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  name text not null,
  slug text not null,
  season text,
  format tournament_format not null default 'round_robin',
  match_format match_format not null default 'T20',
  status tournament_status not null default 'draft',
  /* Visible to signed-out fans on the public web build. */
  is_public boolean not null default true,
  logo_url text,
  banner_url text,
  description text,
  start_date date,
  end_date date,
  group_count int not null default 1,

  -- Playing conditions. Mirrors MatchRules in src/domain/types.ts.
  overs_per_innings int default 20,
  balls_per_over int not null default 6,
  wide_runs int not null default 1,
  no_ball_runs int not null default 1,
  free_hit_after_no_ball boolean not null default true,
  players_per_side int not null default 11,
  max_overs_per_bowler int default 4,

  -- Points configuration.
  points_win int not null default 2,
  points_loss int not null default 0,
  points_tie int not null default 1,
  points_no_result int not null default 1,
  bonus_point_enabled boolean not null default false,
  bonus_point_ratio numeric(4, 2) not null default 1.25,

  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug),
  constraint overs_positive check (overs_per_innings is null or overs_per_innings > 0),
  constraint balls_per_over_sane check (balls_per_over between 1 and 12)
);

create index on tournaments (organization_id);
create index on tournaments (status);

create table tournament_teams (
  tournament_id uuid not null references tournaments (id) on delete cascade,
  team_id uuid not null references teams (id) on delete cascade,
  group_label text,
  seed int,
  registered_at timestamptz not null default now(),
  primary key (tournament_id, team_id)
);

create index on tournament_teams (team_id);

-- ---------------------------------------------------------------------------
-- Matches
-- ---------------------------------------------------------------------------

create table matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid references tournaments (id) on delete cascade,
  organization_id uuid not null references organizations (id) on delete cascade,
  home_team_id uuid references teams (id) on delete set null,
  away_team_id uuid references teams (id) on delete set null,
  venue_id uuid references venues (id) on delete set null,
  status match_status not null default 'scheduled',
  stage match_stage not null default 'league',
  round int not null default 1,
  match_order int not null default 1,
  label text,
  group_label text,
  scheduled_at timestamptz,

  -- Playing conditions, copied from the tournament so a rain-reduced or
  -- one-off match can differ without rewriting the competition rules.
  overs_per_innings int,
  balls_per_over int not null default 6,
  wide_runs int not null default 1,
  no_ball_runs int not null default 1,
  free_hit_after_no_ball boolean not null default true,
  players_per_side int not null default 11,
  max_overs_per_bowler int,

  -- Toss
  toss_winner_team_id uuid references teams (id) on delete set null,
  toss_decision text check (toss_decision in ('bat', 'bowl')),

  -- Result
  result_kind result_kind,
  winner_team_id uuid references teams (id) on delete set null,
  result_summary text,
  result_margin_runs int,
  result_margin_wickets int,
  player_of_match_id uuid references players (id) on delete set null,

  stream_url text,
  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teams_differ check (home_team_id is null or away_team_id is null or home_team_id <> away_team_id)
);

create index on matches (tournament_id);
create index on matches (organization_id);
create index on matches (status);
create index on matches (scheduled_at);

-- Scorers and umpires assigned to a specific match.
create table match_officials (
  match_id uuid not null references matches (id) on delete cascade,
  user_id uuid not null references profiles (id) on delete cascade,
  role app_role not null check (role in ('scorer', 'umpire', 'stream_operator')),
  assigned_at timestamptz not null default now(),
  primary key (match_id, user_id, role)
);

create index on match_officials (user_id);

-- The eleven (or however many) named for this match.
create table playing_xi (
  match_id uuid not null references matches (id) on delete cascade,
  team_id uuid not null references teams (id) on delete cascade,
  player_id uuid not null references players (id) on delete cascade,
  batting_order int,
  is_captain boolean not null default false,
  is_wicket_keeper boolean not null default false,
  is_substitute boolean not null default false,
  primary key (match_id, player_id)
);

create index on playing_xi (match_id, team_id);

-- ---------------------------------------------------------------------------
-- Innings and deliveries
-- ---------------------------------------------------------------------------

create table innings (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references matches (id) on delete cascade,
  /* 1 or 2 in a limited-overs match; up to 4 in a multi-day match. */
  innings_number int not null check (innings_number between 1 and 4),
  batting_team_id uuid not null references teams (id) on delete cascade,
  bowling_team_id uuid not null references teams (id) on delete cascade,
  /* Set for the side batting second. */
  target int,
  /* Overs this innings was reduced to by rain. */
  reduced_overs int,
  /* DLS or manually revised target. */
  revised_target int,
  closed boolean not null default false,
  end_reason innings_end_reason,
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  unique (match_id, innings_number)
);

create index on innings (match_id);

create table deliveries (
  id uuid primary key default gen_random_uuid(),
  innings_id uuid not null references innings (id) on delete cascade,
  match_id uuid not null references matches (id) on delete cascade,

  /* Server-assigned monotonic order within the innings. */
  sequence int not null,
  over_number int not null default 0,
  ball_in_over int not null default 0,

  striker_id uuid not null references players (id) on delete restrict,
  non_striker_id uuid not null references players (id) on delete restrict,
  bowler_id uuid not null references players (id) on delete restrict,

  runs_off_bat int not null default 0 check (runs_off_bat >= 0),
  /* Absolute wide total including the automatic penalty. NULL when not a wide. */
  wide_runs int check (wide_runs is null or wide_runs > 0),
  /* Absolute no-ball penalty. NULL when not a no ball. */
  no_ball_runs int check (no_ball_runs is null or no_ball_runs > 0),
  byes int not null default 0 check (byes >= 0),
  leg_byes int not null default 0 check (leg_byes >= 0),
  penalty_runs int not null default 0 check (penalty_runs >= 0),

  wicket_kind dismissal_kind,
  player_out_id uuid references players (id) on delete restrict,
  fielder_id uuid references players (id) on delete set null,

  free_hit boolean not null default false,

  -- Derived, so scorecard views need no rule lookups.
  is_legal boolean generated always as (wide_runs is null and no_ball_runs is null) stored,
  total_runs int generated always as (
    runs_off_bat + coalesce(wide_runs, 0) + coalesce(no_ball_runs, 0)
      + byes + leg_byes + penalty_runs
  ) stored,
  bowler_runs int generated always as (
    runs_off_bat + coalesce(wide_runs, 0) + coalesce(no_ball_runs, 0)
  ) stored,

  /* Client-generated. Makes a retried offline sync a no-op instead of a duplicate. */
  idempotency_key text not null,
  recorded_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),

  constraint striker_differs check (striker_id <> non_striker_id),
  constraint wicket_needs_player check (
    (wicket_kind is null and player_out_id is null)
    or (wicket_kind is not null and player_out_id is not null)
  ),
  unique (innings_id, idempotency_key),
  unique (innings_id, sequence)
);

create index on deliveries (innings_id, sequence);
create index on deliveries (match_id);
create index on deliveries (bowler_id);
create index on deliveries (striker_id);

-- Every edit or deletion of a recorded ball, for dispute resolution.
create table score_corrections (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references matches (id) on delete cascade,
  delivery_id uuid,
  action text not null check (action in ('edit', 'delete', 'insert')),
  before_state jsonb,
  after_state jsonb,
  reason text,
  performed_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index on score_corrections (match_id);

-- ---------------------------------------------------------------------------
-- Communication
-- ---------------------------------------------------------------------------

create table channels (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  tournament_id uuid references tournaments (id) on delete cascade,
  match_id uuid references matches (id) on delete cascade,
  name text not null,
  kind text not null default 'tournament' check (kind in ('tournament', 'match', 'team', 'officials')),
  created_at timestamptz not null default now()
);

create index on channels (tournament_id);

create table messages (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references channels (id) on delete cascade,
  author_id uuid references profiles (id) on delete set null,
  body text not null check (length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index on messages (channel_id, created_at desc);

create table notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles (id) on delete cascade,
  title text not null,
  body text,
  kind text not null default 'general',
  match_id uuid references matches (id) on delete cascade,
  tournament_id uuid references tournaments (id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index on notifications (user_id, created_at desc);

create table device_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles (id) on delete cascade,
  expo_push_token text not null,
  platform text,
  last_seen_at timestamptz not null default now(),
  unique (user_id, expo_push_token)
);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Keep updated_at honest.
create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch before update on profiles
  for each row execute function touch_updated_at();
create trigger tournaments_touch before update on tournaments
  for each row execute function touch_updated_at();
create trigger matches_touch before update on matches
  for each row execute function touch_updated_at();

-- Give every new auth user a profile.
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.phone
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Assign each delivery the next sequence number in its innings, and derive the
-- over/ball position. Doing this server-side means two scorers racing on a
-- flaky connection cannot both claim ball 4 of the 12th over.
create or replace function assign_delivery_position()
returns trigger
language plpgsql
as $$
declare
  next_seq int;
  legal_before int;
  bpo int;
begin
  select coalesce(max(sequence), 0) + 1 into next_seq
  from deliveries where innings_id = new.innings_id;

  new.sequence := next_seq;

  select m.balls_per_over into bpo
  from innings i join matches m on m.id = i.match_id
  where i.id = new.innings_id;

  bpo := coalesce(bpo, 6);

  select count(*) into legal_before
  from deliveries
  where innings_id = new.innings_id and is_legal;

  if new.wide_runs is null and new.no_ball_runs is null then
    new.over_number := legal_before / bpo;
    new.ball_in_over := (legal_before % bpo) + 1;
  else
    new.over_number := legal_before / bpo;
    new.ball_in_over := (legal_before % bpo) + 1;
  end if;

  return new;
end;
$$;

create trigger deliveries_assign_position
  before insert on deliveries
  for each row execute function assign_delivery_position();

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table deliveries;
alter publication supabase_realtime add table innings;
alter publication supabase_realtime add table matches;
alter publication supabase_realtime add table messages;

-- <<< END migrations/20260101000000_init.sql


-- >>> BEGIN migrations/20260101000001_rls.sql

-- ============================================================================
-- Cricket Arena — row level security
-- ============================================================================
-- Model
--
--   Reading sport is public. Scores, fixtures, rosters and points tables are
--   readable by anyone, including signed-out fans on the web build, except for
--   tournaments still marked private.
--
--   Writing sport is narrow. Only an organisation's admins can shape a
--   competition, and only officials assigned to a specific match may record a
--   ball in it.
--
-- All membership lookups go through SECURITY DEFINER helpers. A policy on
-- organization_members that itself queries organization_members would recurse
-- forever; the helpers run with the definer's rights and so bypass RLS.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function auth_is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_platform_admin from profiles where id = auth.uid()), false);
$$;

create or replace function auth_is_org_member(org uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth_is_platform_admin()
     or exists (
       select 1 from organization_members
       where organization_id = org and user_id = auth.uid()
     );
$$;

create or replace function auth_has_org_role(org uuid, allowed app_role[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth_is_platform_admin()
     or exists (
       select 1 from organization_members
       where organization_id = org
         and user_id = auth.uid()
         and role = any (allowed)
     );
$$;

-- Shorthand for "may configure this competition".
create or replace function auth_is_org_admin(org uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth_has_org_role(org, array['tournament_admin']::app_role[]);
$$;

-- May this user record balls in this match?
create or replace function auth_can_score_match(match uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from matches m
    where m.id = match
      and (
        auth_is_org_admin(m.organization_id)
        or exists (
          select 1 from match_officials o
          where o.match_id = m.id
            and o.user_id = auth.uid()
            and o.role = 'scorer'
        )
      )
  );
$$;

-- May this user see this match? Private tournaments are members-only.
create or replace function auth_can_read_match(match uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from matches m
    left join tournaments t on t.id = m.tournament_id
    where m.id = match
      and (t.id is null or t.is_public or auth_is_org_member(m.organization_id))
  );
$$;

-- Whoever creates an organisation becomes its first administrator.
create or replace function handle_new_organization()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.created_by is not null then
    insert into organization_members (organization_id, user_id, role)
    values (new.id, new.created_by, 'tournament_admin')
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create trigger on_organization_created
  after insert on organizations
  for each row execute function handle_new_organization();

-- ---------------------------------------------------------------------------
-- Enable RLS everywhere
-- ---------------------------------------------------------------------------

alter table profiles              enable row level security;
alter table organizations         enable row level security;
alter table organization_members  enable row level security;
alter table venues                enable row level security;
alter table teams                 enable row level security;
alter table players               enable row level security;
alter table team_members          enable row level security;
alter table tournaments           enable row level security;
alter table tournament_teams      enable row level security;
alter table matches               enable row level security;
alter table match_officials       enable row level security;
alter table playing_xi            enable row level security;
alter table innings               enable row level security;
alter table deliveries            enable row level security;
alter table score_corrections     enable row level security;
alter table channels              enable row level security;
alter table messages              enable row level security;
alter table notifications         enable row level security;
alter table device_sessions       enable row level security;

-- ---------------------------------------------------------------------------
-- Profiles
-- ---------------------------------------------------------------------------

create policy profiles_read on profiles
  for select using (true);

create policy profiles_update_own on profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

-- The sign-up trigger inserts the row; this covers a manual repair.
create policy profiles_insert_own on profiles
  for insert with check (id = auth.uid());

-- ---------------------------------------------------------------------------
-- Organisations
-- ---------------------------------------------------------------------------

create policy organizations_read on organizations
  for select using (true);

create policy organizations_insert on organizations
  for insert to authenticated
  with check (created_by = auth.uid());

create policy organizations_update on organizations
  for update using (auth_is_org_admin(id));

create policy organizations_delete on organizations
  for delete using (auth_is_org_admin(id));

create policy org_members_read on organization_members
  for select using (auth_is_org_member(organization_id) or user_id = auth.uid());

create policy org_members_write on organization_members
  for all using (auth_is_org_admin(organization_id))
  with check (auth_is_org_admin(organization_id));

-- ---------------------------------------------------------------------------
-- Rosters and venues: public to read, admins to write
-- ---------------------------------------------------------------------------

create policy venues_read on venues for select using (true);
create policy venues_write on venues
  for all using (auth_is_org_admin(organization_id))
  with check (auth_is_org_admin(organization_id));

create policy teams_read on teams for select using (true);

create policy teams_write on teams
  for all
  using (
    auth_is_org_admin(organization_id)
    or manager_id = auth.uid()
  )
  with check (
    auth_is_org_admin(organization_id)
    or manager_id = auth.uid()
  );

create policy players_read on players for select using (true);

create policy players_write on players
  for all
  using (
    auth_has_org_role(organization_id, array['tournament_admin', 'team_manager']::app_role[])
  )
  with check (
    auth_has_org_role(organization_id, array['tournament_admin', 'team_manager']::app_role[])
  );

-- A player may maintain their own record once it is linked to their account.
create policy players_update_self on players
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy team_members_read on team_members for select using (true);

create policy team_members_write on team_members
  for all
  using (
    exists (
      select 1 from teams t
      where t.id = team_id
        and (auth_has_org_role(t.organization_id, array['tournament_admin', 'team_manager']::app_role[])
             or t.manager_id = auth.uid())
    )
  )
  with check (
    exists (
      select 1 from teams t
      where t.id = team_id
        and (auth_has_org_role(t.organization_id, array['tournament_admin', 'team_manager']::app_role[])
             or t.manager_id = auth.uid())
    )
  );

-- ---------------------------------------------------------------------------
-- Tournaments
-- ---------------------------------------------------------------------------

create policy tournaments_read on tournaments
  for select using (is_public or auth_is_org_member(organization_id));

create policy tournaments_write on tournaments
  for all using (auth_is_org_admin(organization_id))
  with check (auth_is_org_admin(organization_id));

create policy tournament_teams_read on tournament_teams
  for select using (
    exists (
      select 1 from tournaments t
      where t.id = tournament_id
        and (t.is_public or auth_is_org_member(t.organization_id))
    )
  );

create policy tournament_teams_write on tournament_teams
  for all
  using (
    exists (select 1 from tournaments t where t.id = tournament_id and auth_is_org_admin(t.organization_id))
  )
  with check (
    exists (select 1 from tournaments t where t.id = tournament_id and auth_is_org_admin(t.organization_id))
  );

-- ---------------------------------------------------------------------------
-- Matches
-- ---------------------------------------------------------------------------

create policy matches_read on matches
  for select using (
    tournament_id is null
    or exists (
      select 1 from tournaments t
      where t.id = tournament_id
        and (t.is_public or auth_is_org_member(t.organization_id))
    )
  );

create policy matches_write on matches
  for all using (auth_is_org_admin(organization_id))
  with check (auth_is_org_admin(organization_id));

-- A scorer may move the match through its states (toss, live, completed)
-- without being able to create or delete fixtures.
create policy matches_update_by_scorer on matches
  for update using (auth_can_score_match(id)) with check (auth_can_score_match(id));

create policy match_officials_read on match_officials
  for select using (auth_can_read_match(match_id));

create policy match_officials_write on match_officials
  for all
  using (exists (select 1 from matches m where m.id = match_id and auth_is_org_admin(m.organization_id)))
  with check (exists (select 1 from matches m where m.id = match_id and auth_is_org_admin(m.organization_id)));

create policy playing_xi_read on playing_xi
  for select using (auth_can_read_match(match_id));

create policy playing_xi_write on playing_xi
  for all using (auth_can_score_match(match_id)) with check (auth_can_score_match(match_id));

-- ---------------------------------------------------------------------------
-- Scoring
-- ---------------------------------------------------------------------------

create policy innings_read on innings
  for select using (auth_can_read_match(match_id));

create policy innings_write on innings
  for all using (auth_can_score_match(match_id)) with check (auth_can_score_match(match_id));

create policy deliveries_read on deliveries
  for select using (auth_can_read_match(match_id));

create policy deliveries_insert on deliveries
  for insert to authenticated
  with check (auth_can_score_match(match_id) and recorded_by = auth.uid());

-- Corrections stay possible, but every one is written to score_corrections by
-- the client and both are visible to the organiser.
create policy deliveries_update on deliveries
  for update using (auth_can_score_match(match_id)) with check (auth_can_score_match(match_id));

create policy deliveries_delete on deliveries
  for delete using (auth_can_score_match(match_id));

create policy corrections_read on score_corrections
  for select using (auth_can_read_match(match_id));

create policy corrections_insert on score_corrections
  for insert to authenticated
  with check (auth_can_score_match(match_id) and performed_by = auth.uid());

-- ---------------------------------------------------------------------------
-- Communication
-- ---------------------------------------------------------------------------

create policy channels_read on channels
  for select using (
    tournament_id is null
    or exists (
      select 1 from tournaments t
      where t.id = tournament_id and (t.is_public or auth_is_org_member(t.organization_id))
    )
  );

create policy channels_write on channels
  for all using (auth_is_org_admin(organization_id))
  with check (auth_is_org_admin(organization_id));

create policy messages_read on messages
  for select using (
    exists (
      select 1 from channels c
      left join tournaments t on t.id = c.tournament_id
      where c.id = channel_id
        and (t.id is null or t.is_public or auth_is_org_member(c.organization_id))
    )
  );

create policy messages_insert on messages
  for insert to authenticated
  with check (
    author_id = auth.uid()
    and exists (
      select 1 from channels c
      where c.id = channel_id and auth_is_org_member(c.organization_id)
    )
  );

create policy messages_delete_own on messages
  for delete using (
    author_id = auth.uid()
    or exists (select 1 from channels c where c.id = channel_id and auth_is_org_admin(c.organization_id))
  );

-- ---------------------------------------------------------------------------
-- Personal data: strictly the owner's
-- ---------------------------------------------------------------------------

create policy notifications_read on notifications
  for select using (user_id = auth.uid());

create policy notifications_update on notifications
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy notifications_delete on notifications
  for delete using (user_id = auth.uid());

create policy device_sessions_own on device_sessions
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- <<< END migrations/20260101000001_rls.sql


-- >>> BEGIN migrations/20260101000002_views.sql

-- ============================================================================
-- Cricket Arena — derived views
-- ============================================================================
-- Scorecards, points tables and career figures are all folded out of the
-- delivery log here rather than kept in maintained tables. That means there is
-- exactly one definition of "runs conceded" and it cannot drift out of step
-- with the balls that were actually bowled.
--
-- Every view is created with security_invoker so it enforces the caller's RLS
-- rather than the view owner's.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Innings totals
-- ---------------------------------------------------------------------------

create view innings_scores
with (security_invoker = on) as
select
  i.id as innings_id,
  i.match_id,
  i.innings_number,
  i.batting_team_id,
  i.bowling_team_id,
  i.target,
  i.closed,
  i.end_reason,
  coalesce(sum(d.total_runs), 0)::int as runs,
  count(*) filter (
    where d.wicket_kind is not null and d.wicket_kind <> 'retired_not_out'
  )::int as wickets,
  count(*) filter (where d.is_legal)::int as legal_balls,
  coalesce(sum(d.wide_runs), 0)::int as wides,
  coalesce(sum(d.no_ball_runs), 0)::int as no_balls,
  coalesce(sum(d.byes), 0)::int as byes,
  coalesce(sum(d.leg_byes), 0)::int as leg_byes,
  coalesce(sum(d.penalty_runs), 0)::int as penalties,
  coalesce(sum(d.wide_runs), 0)::int
    + coalesce(sum(d.no_ball_runs), 0)::int
    + coalesce(sum(d.byes), 0)::int
    + coalesce(sum(d.leg_byes), 0)::int
    + coalesce(sum(d.penalty_runs), 0)::int as extras
from innings i
left join deliveries d on d.innings_id = i.id
group by i.id;

comment on view innings_scores is 'Team totals for one innings, folded from its deliveries.';

-- ---------------------------------------------------------------------------
-- Batting scorecard
-- ---------------------------------------------------------------------------

create view batting_scorecard
with (security_invoker = on) as
with faced as (
  select
    d.innings_id,
    d.striker_id as player_id,
    sum(d.runs_off_bat)::int as runs,
    -- A wide is not a ball faced; a no ball is.
    count(*) filter (where d.wide_runs is null)::int as balls,
    count(*) filter (where d.runs_off_bat = 4)::int as fours,
    count(*) filter (where d.runs_off_bat = 6)::int as sixes,
    count(*) filter (
      where d.is_legal and d.runs_off_bat = 0 and d.byes = 0 and d.leg_byes = 0
    )::int as dots,
    min(d.sequence)::int as first_ball_sequence
  from deliveries d
  group by d.innings_id, d.striker_id
),
dismissals as (
  select
    d.innings_id,
    d.player_out_id as player_id,
    d.wicket_kind,
    d.bowler_id as dismissed_by_bowler_id,
    d.fielder_id,
    d.sequence
  from deliveries d
  where d.player_out_id is not null
)
select
  i.id as innings_id,
  i.match_id,
  i.batting_team_id as team_id,
  p.id as player_id,
  p.full_name,
  coalesce(x.batting_order, row_number() over (partition by i.id order by f.first_ball_sequence)) as batting_position,
  coalesce(f.runs, 0) as runs,
  coalesce(f.balls, 0) as balls,
  coalesce(f.fours, 0) as fours,
  coalesce(f.sixes, 0) as sixes,
  coalesce(f.dots, 0) as dots,
  case when coalesce(f.balls, 0) > 0
    then round((coalesce(f.runs, 0)::numeric / f.balls) * 100, 2)
    else 0 end as strike_rate,
  (dm.wicket_kind is not null and dm.wicket_kind <> 'retired_not_out') as is_out,
  dm.wicket_kind,
  dm.dismissed_by_bowler_id,
  dm.fielder_id
from innings i
join playing_xi x on x.match_id = i.match_id and x.team_id = i.batting_team_id
join players p on p.id = x.player_id
left join faced f on f.innings_id = i.id and f.player_id = p.id
left join dismissals dm on dm.innings_id = i.id and dm.player_id = p.id
where f.player_id is not null or dm.player_id is not null or x.batting_order is not null;

-- ---------------------------------------------------------------------------
-- Bowling scorecard
-- ---------------------------------------------------------------------------

create view bowling_scorecard
with (security_invoker = on) as
with per_over as (
  select
    d.innings_id,
    d.bowler_id,
    d.over_number,
    sum(d.bowler_runs)::int as runs_in_over,
    count(*) filter (where d.is_legal)::int as legal_in_over
  from deliveries d
  group by d.innings_id, d.bowler_id, d.over_number
),
totals as (
  select
    d.innings_id,
    d.bowler_id,
    count(*) filter (where d.is_legal)::int as legal_balls,
    sum(d.bowler_runs)::int as runs_conceded,
    count(*) filter (
      where d.wicket_kind in ('bowled','caught','caught_behind','caught_and_bowled','lbw','stumped','hit_wicket')
    )::int as wickets,
    coalesce(sum(d.wide_runs), 0)::int as wides,
    count(*) filter (where d.no_ball_runs is not null)::int as no_balls,
    count(*) filter (where d.is_legal and d.bowler_runs = 0)::int as dots
  from deliveries d
  group by d.innings_id, d.bowler_id
),
maidens as (
  select
    o.innings_id,
    o.bowler_id,
    count(*)::int as maidens
  from per_over o
  join innings i on i.id = o.innings_id
  join matches m on m.id = i.match_id
  where o.runs_in_over = 0 and o.legal_in_over >= m.balls_per_over
  group by o.innings_id, o.bowler_id
)
select
  t.innings_id,
  i.match_id,
  i.bowling_team_id as team_id,
  t.bowler_id as player_id,
  p.full_name,
  t.legal_balls,
  (t.legal_balls / m.balls_per_over)::text || '.' || (t.legal_balls % m.balls_per_over)::text as overs,
  t.runs_conceded,
  t.wickets,
  coalesce(mn.maidens, 0) as maidens,
  t.wides,
  t.no_balls,
  t.dots,
  case when t.legal_balls > 0
    then round(t.runs_conceded::numeric / (t.legal_balls::numeric / m.balls_per_over), 2)
    else 0 end as economy
from totals t
join innings i on i.id = t.innings_id
join matches m on m.id = i.match_id
join players p on p.id = t.bowler_id
left join maidens mn on mn.innings_id = t.innings_id and mn.bowler_id = t.bowler_id;

-- ---------------------------------------------------------------------------
-- Match summary: one row per match with both innings folded in
-- ---------------------------------------------------------------------------

create view match_summaries
with (security_invoker = on) as
select
  m.id as match_id,
  m.tournament_id,
  m.organization_id,
  m.status,
  m.stage,
  m.round,
  m.label,
  m.scheduled_at,
  m.overs_per_innings,
  m.balls_per_over,
  m.home_team_id,
  ht.name as home_team_name,
  ht.short_name as home_team_short,
  ht.primary_color as home_team_color,
  m.away_team_id,
  at.name as away_team_name,
  at.short_name as away_team_short,
  at.primary_color as away_team_color,
  v.name as venue_name,
  m.result_kind,
  m.winner_team_id,
  m.result_summary,
  i1.batting_team_id as first_innings_team_id,
  i1.runs as first_innings_runs,
  i1.wickets as first_innings_wickets,
  i1.legal_balls as first_innings_balls,
  i2.batting_team_id as second_innings_team_id,
  i2.runs as second_innings_runs,
  i2.wickets as second_innings_wickets,
  i2.legal_balls as second_innings_balls,
  i2.target as chase_target
from matches m
left join teams ht on ht.id = m.home_team_id
left join teams at on at.id = m.away_team_id
left join venues v on v.id = m.venue_id
left join innings_scores i1 on i1.match_id = m.id and i1.innings_number = 1
left join innings_scores i2 on i2.match_id = m.id and i2.innings_number = 2;

-- ---------------------------------------------------------------------------
-- Points table
-- ---------------------------------------------------------------------------

-- One row per side per completed match, from that side's point of view.
create view team_match_records
with (security_invoker = on) as
select
  m.id as match_id,
  m.tournament_id,
  own.batting_team_id as team_id,
  own.bowling_team_id as opponent_id,
  case
    when m.result_kind = 'walkover' and m.winner_team_id = own.batting_team_id then 'walkover_win'
    when m.result_kind = 'walkover' then 'walkover_loss'
    when m.result_kind = 'tie' then 'tie'
    when m.result_kind in ('no_result', 'abandoned', 'draw') then 'no_result'
    when m.winner_team_id = own.batting_team_id then 'win'
    else 'loss'
  end as outcome,
  own.runs as runs_scored,
  own.legal_balls as balls_faced,
  (own.wickets >= m.players_per_side - 1) as all_out,
  coalesce(opp.runs, 0) as runs_conceded,
  coalesce(opp.legal_balls, 0) as balls_bowled,
  coalesce(opp.wickets >= m.players_per_side - 1, false) as opponent_all_out,
  m.overs_per_innings as max_overs,
  m.balls_per_over
from matches m
join innings_scores own on own.match_id = m.id
left join innings_scores opp
  on opp.match_id = m.id and opp.batting_team_id = own.bowling_team_id
where m.status in ('completed', 'walkover', 'abandoned')
  and m.result_kind is not null;

create view tournament_standings
with (security_invoker = on) as
with charged as (
  select
    r.*,
    -- A side bowled out is charged its full quota of overs, not the overs it
    -- actually faced. Without this, being dismissed cheaply would flatter a
    -- team's run rate.
    case
      when r.all_out and r.max_overs is not null then r.max_overs::numeric
      else r.balls_faced::numeric / nullif(r.balls_per_over, 0)
    end as overs_faced,
    case
      when r.opponent_all_out and r.max_overs is not null then r.max_overs::numeric
      else r.balls_bowled::numeric / nullif(r.balls_per_over, 0)
    end as overs_bowled
  from team_match_records r
),
agg as (
  select
    c.tournament_id,
    c.team_id,
    count(*)::int as played,
    count(*) filter (where c.outcome in ('win', 'walkover_win'))::int as won,
    count(*) filter (where c.outcome in ('loss', 'walkover_loss'))::int as lost,
    count(*) filter (where c.outcome = 'tie')::int as tied,
    count(*) filter (where c.outcome = 'no_result')::int as no_result,
    sum(c.runs_scored) filter (where c.outcome not in ('no_result', 'walkover_win', 'walkover_loss'))::int as runs_scored,
    sum(c.overs_faced) filter (where c.outcome not in ('no_result', 'walkover_win', 'walkover_loss')) as overs_faced,
    sum(c.runs_conceded) filter (where c.outcome not in ('no_result', 'walkover_win', 'walkover_loss'))::int as runs_conceded,
    sum(c.overs_bowled) filter (where c.outcome not in ('no_result', 'walkover_win', 'walkover_loss')) as overs_bowled
  from charged c
  group by c.tournament_id, c.team_id
)
select
  a.tournament_id,
  a.team_id,
  t.name as team_name,
  t.short_name as team_short,
  t.primary_color as team_color,
  tt.group_label,
  a.played,
  a.won,
  a.lost,
  a.tied,
  a.no_result,
  (a.won * tr.points_win
    + a.lost * tr.points_loss
    + a.tied * tr.points_tie
    + a.no_result * tr.points_no_result)::int as points,
  coalesce(a.runs_scored, 0) as runs_scored,
  round(coalesce(a.overs_faced, 0), 1) as overs_faced,
  coalesce(a.runs_conceded, 0) as runs_conceded,
  round(coalesce(a.overs_bowled, 0), 1) as overs_bowled,
  round(
    coalesce(a.runs_scored::numeric / nullif(a.overs_faced, 0), 0)
      - coalesce(a.runs_conceded::numeric / nullif(a.overs_bowled, 0), 0),
    3
  ) as net_run_rate
from agg a
join teams t on t.id = a.team_id
join tournaments tr on tr.id = a.tournament_id
left join tournament_teams tt on tt.tournament_id = a.tournament_id and tt.team_id = a.team_id;

-- ---------------------------------------------------------------------------
-- Career figures
-- ---------------------------------------------------------------------------

create view player_batting_career
with (security_invoker = on) as
select
  b.player_id,
  p.full_name,
  p.organization_id,
  m.tournament_id,
  count(*)::int as innings,
  count(*) filter (where not b.is_out)::int as not_outs,
  sum(b.runs)::int as runs,
  sum(b.balls)::int as balls,
  sum(b.fours)::int as fours,
  sum(b.sixes)::int as sixes,
  count(*) filter (where b.runs >= 50 and b.runs < 100)::int as fifties,
  count(*) filter (where b.runs >= 100)::int as hundreds,
  max(b.runs)::int as high_score,
  case when count(*) filter (where b.is_out) > 0
    then round(sum(b.runs)::numeric / count(*) filter (where b.is_out), 2)
    else null end as average,
  case when sum(b.balls) > 0
    then round((sum(b.runs)::numeric / sum(b.balls)) * 100, 2)
    else 0 end as strike_rate
from batting_scorecard b
join players p on p.id = b.player_id
join matches m on m.id = b.match_id
where b.balls > 0 or b.is_out
group by b.player_id, p.full_name, p.organization_id, m.tournament_id;

create view player_bowling_career
with (security_invoker = on) as
select
  b.player_id,
  p.full_name,
  p.organization_id,
  m.tournament_id,
  count(*)::int as innings,
  sum(b.legal_balls)::int as legal_balls,
  sum(b.runs_conceded)::int as runs_conceded,
  sum(b.wickets)::int as wickets,
  sum(b.maidens)::int as maidens,
  max(b.wickets)::int as best_wickets,
  count(*) filter (where b.wickets >= 4 and b.wickets < 5)::int as four_wicket_hauls,
  count(*) filter (where b.wickets >= 5)::int as five_wicket_hauls,
  case when sum(b.wickets) > 0
    then round(sum(b.runs_conceded)::numeric / sum(b.wickets), 2)
    else null end as average,
  case when sum(b.legal_balls) > 0
    then round(sum(b.runs_conceded)::numeric / (sum(b.legal_balls)::numeric / max(m.balls_per_over)), 2)
    else 0 end as economy,
  case when sum(b.wickets) > 0
    then round(sum(b.legal_balls)::numeric / sum(b.wickets), 1)
    else null end as strike_rate
from bowling_scorecard b
join players p on p.id = b.player_id
join matches m on m.id = b.match_id
group by b.player_id, p.full_name, p.organization_id, m.tournament_id;

-- ---------------------------------------------------------------------------
-- Helper RPCs
-- ---------------------------------------------------------------------------

-- Record a delivery and return the row with its server-assigned sequence.
-- Wrapping the insert means an offline queue can retry blindly: the unique
-- (innings_id, idempotency_key) index turns a duplicate into a no-op that
-- returns the ball already stored.
create or replace function record_delivery(payload jsonb)
returns deliveries
language plpgsql
security invoker
as $$
declare
  result deliveries;
  key text := payload ->> 'idempotency_key';
  innings uuid := (payload ->> 'innings_id')::uuid;
begin
  select * into result from deliveries
  where innings_id = innings and idempotency_key = key;

  if found then
    return result;
  end if;

  insert into deliveries (
    innings_id, match_id, striker_id, non_striker_id, bowler_id,
    runs_off_bat, wide_runs, no_ball_runs, byes, leg_byes, penalty_runs,
    wicket_kind, player_out_id, fielder_id, free_hit,
    idempotency_key, recorded_by
  )
  values (
    innings,
    (payload ->> 'match_id')::uuid,
    (payload ->> 'striker_id')::uuid,
    (payload ->> 'non_striker_id')::uuid,
    (payload ->> 'bowler_id')::uuid,
    coalesce((payload ->> 'runs_off_bat')::int, 0),
    (payload ->> 'wide_runs')::int,
    (payload ->> 'no_ball_runs')::int,
    coalesce((payload ->> 'byes')::int, 0),
    coalesce((payload ->> 'leg_byes')::int, 0),
    coalesce((payload ->> 'penalty_runs')::int, 0),
    (payload ->> 'wicket_kind')::dismissal_kind,
    (payload ->> 'player_out_id')::uuid,
    (payload ->> 'fielder_id')::uuid,
    coalesce((payload ->> 'free_hit')::boolean, false),
    key,
    auth.uid()
  )
  on conflict (innings_id, idempotency_key) do nothing
  returning * into result;

  if result.id is null then
    select * into result from deliveries
    where innings_id = innings and idempotency_key = key;
  end if;

  return result;
end;
$$;

grant execute on function record_delivery(jsonb) to authenticated;

-- <<< END migrations/20260101000002_views.sql


-- >>> BEGIN migrations/20260101000003_registrations.sql

-- ============================================================================
-- Cricket Arena — player self-registration, following, and avatars
-- ============================================================================
-- Three additions:
--
-- 1. `player_registrations` lets a cricketer apply to join a squad themselves.
--    Nothing they submit touches the real roster until an organiser approves
--    it, so a stranger cannot insert themselves into a league's statistics.
--
-- 2. `follows` powers the fan experience: follow a team, tournament or player
--    and their fixtures surface on your dashboard.
--
-- 3. An `avatars` storage bucket with policies that keep each user inside
--    their own folder.
-- ============================================================================

create type registration_status as enum ('pending', 'approved', 'rejected', 'withdrawn');

create table player_registrations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  team_id uuid not null references teams (id) on delete cascade,
  /* Optional: applying for a specific competition rather than the club at large. */
  tournament_id uuid references tournaments (id) on delete set null,
  /* The account making the application. */
  user_id uuid not null references profiles (id) on delete cascade,
  /* Filled in on approval, linking the application to the roster entry it created. */
  player_id uuid references players (id) on delete set null,

  full_name text not null check (length(trim(full_name)) >= 2),
  display_name text,
  jersey_number int check (jersey_number is null or jersey_number between 0 and 999),
  date_of_birth date,
  phone text,
  photo_url text,
  role player_role not null default 'batter',
  batting_style batting_style not null default 'right_hand',
  bowling_style bowling_style not null default 'none',
  /* A note from the applicant to the organiser. */
  note text check (note is null or length(note) <= 500),

  status registration_status not null default 'pending',
  reviewed_by uuid references profiles (id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),

  -- One open application per person per team. Re-applying after a rejection is
  -- allowed, because the partial index only covers pending rows.
  constraint reviewed_has_reviewer check (
    (status in ('pending', 'withdrawn')) or (reviewed_by is not null and reviewed_at is not null)
  )
);

create unique index one_pending_application
  on player_registrations (team_id, user_id)
  where status = 'pending';

create index on player_registrations (organization_id, status);
create index on player_registrations (user_id);

-- ---------------------------------------------------------------------------
-- Following
-- ---------------------------------------------------------------------------

create table follows (
  user_id uuid not null references profiles (id) on delete cascade,
  team_id uuid references teams (id) on delete cascade,
  tournament_id uuid references tournaments (id) on delete cascade,
  player_id uuid references players (id) on delete cascade,
  created_at timestamptz not null default now(),
  -- Exactly one target per row.
  constraint one_target check (
    (team_id is not null)::int + (tournament_id is not null)::int + (player_id is not null)::int = 1
  )
);

create unique index follows_team_unique on follows (user_id, team_id) where team_id is not null;
create unique index follows_tournament_unique on follows (user_id, tournament_id) where tournament_id is not null;
create unique index follows_player_unique on follows (user_id, player_id) where player_id is not null;
create index on follows (user_id);

-- ---------------------------------------------------------------------------
-- Approval
-- ---------------------------------------------------------------------------

-- Approving an application has to do three things together — create the player,
-- put them in the squad, and mark the application — so it lives in one function
-- rather than three round trips that could half-fail.
--
-- SECURITY DEFINER because the approving admin needs to write a `players` row
-- on someone else's behalf; the first statement re-checks that they are
-- actually an admin of the owning organisation.
create or replace function approve_registration(registration uuid, note text default null)
returns players
language plpgsql
security definer
set search_path = public
as $$
-- `note` and `registration` shadow columns of player_registrations; the
-- parameter is always what is meant here.
#variable_conflict use_variable
declare
  app player_registrations;
  created players;
begin
  select * into app from player_registrations where id = registration;
  if not found then
    raise exception 'Registration not found';
  end if;

  if not auth_is_org_admin(app.organization_id) then
    raise exception 'Only an administrator of this organisation can approve registrations'
      using errcode = '42501';
  end if;

  if app.status <> 'pending' then
    raise exception 'This registration has already been %', app.status;
  end if;

  -- Reuse an existing roster entry when this account is already a player here,
  -- so someone moving between clubs keeps one career record.
  select * into created from players
  where organization_id = app.organization_id and user_id = app.user_id
  limit 1;

  if not found then
    insert into players (
      organization_id, user_id, full_name, display_name, jersey_number,
      date_of_birth, phone, photo_url, role, batting_style, bowling_style
    )
    values (
      app.organization_id, app.user_id, app.full_name, app.display_name, app.jersey_number,
      app.date_of_birth, app.phone, app.photo_url, app.role, app.batting_style, app.bowling_style
    )
    returning * into created;
  end if;

  insert into team_members (team_id, player_id)
  values (app.team_id, created.id)
  on conflict do nothing;

  update player_registrations
  set status = 'approved',
      player_id = created.id,
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      review_note = note
  where id = registration;

  -- Give the applicant a role in the organisation so the app stops treating
  -- them as an anonymous fan.
  insert into organization_members (organization_id, user_id, role)
  values (app.organization_id, app.user_id, 'player')
  on conflict do nothing;

  return created;
end;
$$;

create or replace function reject_registration(registration uuid, note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_variable
declare
  org uuid;
begin
  select organization_id into org from player_registrations where id = registration;
  if org is null then
    raise exception 'Registration not found';
  end if;
  if not auth_is_org_admin(org) then
    raise exception 'Only an administrator of this organisation can reject registrations'
      using errcode = '42501';
  end if;

  update player_registrations
  set status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now(), review_note = note
  where id = registration and status = 'pending';
end;
$$;

grant execute on function approve_registration(uuid, text) to authenticated;
grant execute on function reject_registration(uuid, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------
-- `notifications` deliberately has no INSERT policy: rows are only ever created
-- by these triggers, so nobody can spam another user's inbox through the API.

create or replace function notify_registration_submitted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  team_name text;
  admin_id uuid;
begin
  select name into team_name from teams where id = new.team_id;

  -- Notify every administrator, and fall back to whoever created the
  -- organisation. Without the fallback an org whose admin role was never
  -- assigned would swallow applications silently.
  for admin_id in
    select om.user_id from organization_members om
    where om.organization_id = new.organization_id and om.role = 'tournament_admin'
    union
    select o.created_by from organizations o
    where o.id = new.organization_id and o.created_by is not null
  loop
    insert into notifications (user_id, title, body, kind, tournament_id)
    values (
      admin_id,
      'New player registration',
      new.full_name || ' has applied to join ' || coalesce(team_name, 'a team') || '.',
      'registration',
      new.tournament_id
    );
  end loop;

  return new;
end;
$$;

create trigger on_registration_submitted
  after insert on player_registrations
  for each row execute function notify_registration_submitted();

create or replace function notify_registration_reviewed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  team_name text;
begin
  if new.status = old.status then
    return new;
  end if;

  select name into team_name from teams where id = new.team_id;

  if new.status = 'approved' then
    insert into notifications (user_id, title, body, kind, tournament_id)
    values (
      new.user_id,
      'You are in the squad',
      'Your registration for ' || coalesce(team_name, 'the team') || ' was approved.'
        || coalesce(' ' || new.review_note, ''),
      'registration',
      new.tournament_id
    );
  elsif new.status = 'rejected' then
    insert into notifications (user_id, title, body, kind, tournament_id)
    values (
      new.user_id,
      'Registration not accepted',
      'Your registration for ' || coalesce(team_name, 'the team') || ' was not accepted.'
        || coalesce(' ' || new.review_note, ''),
      'registration',
      new.tournament_id
    );
  end if;

  return new;
end;
$$;

create trigger on_registration_reviewed
  after update on player_registrations
  for each row execute function notify_registration_reviewed();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table player_registrations enable row level security;
alter table follows enable row level security;

-- An applicant sees their own; organisers see everything sent to them.
create policy registrations_read on player_registrations
  for select using (
    user_id = auth.uid()
    or auth_has_org_role(organization_id, array['tournament_admin', 'team_manager']::app_role[])
  );

-- You may only apply as yourself, and only ever as pending.
create policy registrations_insert on player_registrations
  for insert to authenticated
  with check (user_id = auth.uid() and status = 'pending');

-- The applicant may withdraw. Approving and rejecting go through the functions
-- above, which is why there is no general update policy for organisers here.
create policy registrations_withdraw on player_registrations
  for update using (user_id = auth.uid() and status = 'pending')
  with check (user_id = auth.uid() and status in ('pending', 'withdrawn'));

create policy follows_own on follows
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Avatar storage
-- ---------------------------------------------------------------------------
-- Public read so photos render on the fan-facing web build without a signed
-- URL; writes are confined to a folder named after the user's own id.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152, -- 2 MB is plenty for a resized profile photo
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

create policy "Avatars are publicly readable"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "Users upload their own avatar"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users replace their own avatar"
  on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users delete their own avatar"
  on storage.objects for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table player_registrations;
alter publication supabase_realtime add table notifications;

-- <<< END migrations/20260101000003_registrations.sql

